default:
  image: node:latest

stages:         
  - test
  - build

build-server:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd ./03_code/frontend
    - docker login registry.gitlab.com
    - docker build -t registry.gitlab.com/plan-heig/server .
    - docker push registry.gitlab.com/plan-heig/server
      
    

buid-server-api:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd ./03_code/serverAPI
    - docker login registry.gitlab.com
    - docker build -t registry.gitlab.com/plan-heig/server-api .
    - docker push registry.gitlab.com/plan-heig/server-api



