stages:          # List of stages for jobs, and their order of execution 
  - test
  - build


build-server:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - cd ./03_code/frontend
        - npm run install
        - npm run build
        - cd ..
        # - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        # - docker build -f .\serverAPI\Dockerfile -t plan-heig/server-api .
        # - docker push $CI_REGISTRY_IMAGE:$VERSION
        # - docker push $CI_REGISTRY_IMAGE:latest
    

buid-server-api:
    stage: build
    image: docker:latest
    services:
      - docker:dind
    script:
        - cd ./03_code/
        # - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        # - docker build -f .\serverAPI\Dockerfile -t plan-heig/server-api .
        # - docker push $CI_REGISTRY_IMAGE:$VERSION
        # - docker push $CI_REGISTRY_IMAGE:latest



