default:
  image: node:latest

stages:         
  - test
  - build

build-server:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd ./03_code/frontend
    - docker login registry.gitlab.com -u $GITLAB_USER -p $GITLAB_TOKEN
    - docker build -t registry.gitlab.com/tb-heig/plan-heig-vd/server .
    - docker push registry.gitlab.com/tb-heig/plan-heig-vd/server
      
    

buid-server-api:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd ./03_code/serverAPI
    - docker login registry.gitlab.com -u $GITLAB_USER -p $GITLAB_TOKEN
    - docker build -t registry.gitlab.com/tb-heig/plan-heig-vd/server-api .
    - docker push registry.gitlab.com/tb-heig/plan-heig-vd/server-api



